---

- hosts: all
  vars_files:
         /etc/ansible/confidential
  tasks:

        - name: Copy content of confidential file to new file
          lineinfile: path=/home/saurav049/secret create=yes line="{{ secret_key }}"


